# Generated by Django 3.2.9 on 2021-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/posts/default.jpg', upload_to='images/posts'),
        ),
    ]
