# Generated by Django 3.2.9 on 2021-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socnet', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_avatar/person.png', upload_to='user_avatar'),
        ),
    ]
